name: lash-suite-luxe
region: nyc

databases:
  - name: lash-db
    engine: PG
    production: true
    version: "16"

services:
  # Backend API
  - name: lash-backend
    environment_slug: python
    github:
      repo: YOUR_GITHUB_USERNAME/lash-suite-luxe
      branch: main
      deploy_on_push: true
    source_dir: /lash-backend
    run_command: gunicorn config.wsgi --log-file -
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: CHANGE_THIS_TO_A_SECURE_RANDOM_STRING
      - key: ALLOWED_HOSTS
        value: ${APP_DOMAIN}
      - key: DATABASE_URL
        value: ${lash-db.DATABASE_URL}
      - key: CORS_ALLOWED_ORIGINS
        value: ${frontend.PUBLIC_URL}
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        type: SECRET
        value: YOUR_EMAIL@gmail.com
      - key: EMAIL_HOST_PASSWORD
        type: SECRET
        value: YOUR_EMAIL_APP_PASSWORD
      - key: DEFAULT_FROM_EMAIL
        value: YOUR_EMAIL@gmail.com
    http_port: 8000
    routes:
      - path: /api
    health_check:
      http_path: /api/services/

  # Frontend Static Site
  - name: frontend
    environment_slug: node-js
    github:
      repo: YOUR_GITHUB_USERNAME/lash-suite-luxe
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        value: ${lash-backend.PUBLIC_URL}/api
    routes:
      - path: /
    catchall_document: index.html
