# Generated by Django 6.0.2 on 2026-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Harare', help_text="Customer's location for mobile service", max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='needs_transport',
            field=models.BooleanField(default=False, help_text='Whether transport fee is included'),
        ),
    ]
